alter table DDCA_ATTACHEMENT add constraint FK_DDCA_ATTACHEMENT_ON_CATEGORY foreign key (CATEGORY_ID) references DDCA_ATTACHMENT_CATEGORY(ID);
create index IDX_DDCA_ATTACHEMENT_ON_CATEGORY on DDCA_ATTACHEMENT (CATEGORY_ID);
