-- begin DDCA_ATTACHEMENT
alter table DDCA_ATTACHEMENT add constraint FK_DDCA_ATTACHEMENT_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
create index IDX_DDCA_ATTACHEMENT_ON_FILE on DDCA_ATTACHEMENT (FILE_ID)^
create index IDX_DDCA_ATTACHMENT on DDCA_ATTACHEMENT (ATTACHABLE) ^
-- end DDCA_ATTACHEMENT
